version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: Lathanhtung123
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql